### ISSUE TITLE
tortp-gtk error

### ISSUE THREAD

**Issue by ghost** [AvANa-BBS/freepto-lb#154]
hi,
tortp-gtk start error. terminal error text;

```
~ $ sudo tortp-gtk
Traceback (most recent call last):
  File "/usr/local/bin/tortp-gtk", line 356, in <module>
    icon = Icon()
  File "/usr/local/bin/tortp-gtk", line 90, in __init__
    self.load(None)
  File "/usr/local/bin/tortp-gtk", line 100, in load
    self.window = MainWindow()
  File "/usr/local/bin/tortp-gtk", line 152, in __init__
    info_box = self.get_info_box()
  File "/usr/local/bin/tortp-gtk", line 190, in get_info_box
    tpinfo = TransparentProxyInfoBox()
  File "/usr/local/bin/tortp-gtk", line 218, in __init__
    self.load_model()
  File "/usr/local/bin/tortp-gtk", line 224, in load_model
    exit_node = tortp.get_exit()
TypeError: get_exit() takes exactly 1 argument (0 given)

```

help me?

**Comment by FlashBoot** [comment]
I'm sorry, I just asked the wrong store.
